---
- hosts: all:!localhost
  vars:
    ses_packages:
      - python-setuptools
      - python-virtualenv
      - python-devel
      - autoconf
      - git
      - gcc
      - make
      - jq
      - ca-certificates-suse
      - rng-tools
    # Domain name to use in the deployment. Default assumes properly configured dns name.
    domainname: "{{ ansible_domain | default('openstack.local', True) }}"
  tasks:
    - name: Install extra software
      zypper:
        name: "{{ ses_packages }}"
        state: latest

    - name: Configure /etc/hosts
      lineinfile:
        name: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "{{ ansible_all_ipv6_addresses[0] | default('::1')}} {{ inventory_hostname }}.{{ domainname }} {{ inventory_hostname }} {{ ansible_hostname }}.{{ domainname }} {{ ansible_hostname }}"
        - "{{ ansible_all_ipv4_addresses[0]}} {{ inventory_hostname }}.{{ domainname }} {{ inventory_hostname }} {{ ansible_hostname }}.{{ domainname }} {{ ansible_hostname }}"
