---

- name: Check if credentials are provided
  set_fact:
    caasp_kubeconfig_via_cli: "{{ true if caasp_login_credentials.username and caasp_login_credentials.password else false }}"
  when:
    - caasp_login_credentials is defined
    - caasp_login_credentials.username is defined
    - caasp_login_credentials.password is defined
    - caasp_login_credentials.server_name is defined

- name: Generate kubconfig on caasp node
  shell: |
    caasp-cli login -s \
      https://{{ caasp_login_credentials.server_name }}:{{ caasp_login_credentials.server_port }} \
      -u {{ caasp_login_credentials.username }} -p {{ caasp_login_credentials.password }}
  register: _cli_result
  when:
    - caasp_kubeconfig_via_cli | default(false)

- name: Copy kubeconfig from caasp node to deployer
  fetch:
    src: "{{ansible_user_dir}}/.kube/config"
    dest: "~/.kube/config"
    flat: yes
    mode: "0600"
  when:
    - _cli_result is defined
    - _cli_result | success