---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-shipyard-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-shipyard-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: 1800
  values:
    pod:
      replicas:
        api: 1
        airflow:
          web: 1
          worker: 1
          flower: 1
          scheduler: 1
    conf:
      shipyard:
        base:
          airflow_api_read_timeout: 300
        drydock:
          service_type: armada
        promenade:
          service_type: armada
...
