---
- name: Include developer vars
  include_vars: "{{ playbook_dir }}/../vars/developer-mode.yml"

- name: Get the facts from the deployer node from the worker nodes
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['osh-deployer'] }}"

- name: Configure the hosts for local registry if developer mode is enabled
  lineinfile:
    path: /etc/hosts
    line: |
      "{{ hostvars[groups['osh_deployer'][0]]['ansible_default_ipv4']['address'] | ipaddr('address') }} {{ hostvars[groups['osh_deployer'][0]]['ansible_fqdn'] }} {{ hostvars[groups['osh_deployer'][0]]['ansible_hostname'] }}"

- name: Copy the certificates
  copy:
    src: "{{ socok8s_registry_cert }}"
    dest: "/etc/pki/trust/anchors"
  register: _copiedcert

- name: Refresh ca certs
  command: update-ca-certificates
  when: _copiedcert is changed

- name: Restart docker
  when: _copiedcert is changed
  service:
    name: docker
    state: restarted
