---
- name: Add subvolume setup script
  script: caasp_cp_node_set_subvolumes.sh
  register: _subvolume_setup
  args:
    creates: /var/lib/nova

- name: Reboot machine
  reboot:
    timeout: "{{ caasp_reboot_timeout }}"
  when: _subvolume_setup is changed
