---
- name: Prepare override file
  config_template:
    src: glance.yml.j2
    dest: /tmp/glance-suse.yaml
    config_overrides: "{{ suse_osh_deploy_glance_yaml_overrides }}"
    config_type: yaml

- name: Run the override file
  shell: ./tools/deployment/multinode/100-glance.sh
  environment:
    OSH_EXTRA_HELM_ARGS_GLANCE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_GLANCE' | default('', True) }} -f /tmp/glance-suse.yaml"
  args:
    executable: /bin/bash
    chdir: /opt/openstack-helm
