---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-core
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-core-chart-group-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  description: Common Airship Components
  chart_group:
    - ucp-ingress-soc
    - ucp-mariadb-soc
    - ucp-postgresql-soc
    - ucp-rabbitmq-soc
...
