---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-keystone-chart-group-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  description: Airship Keystone components
  chart_group:
    - ucp-keystone-memcached-soc
    - ucp-keystone-soc
...
