---
# defaults file for suse-airship-deploy

# Location of the kubeconfig file, fetched from velum UI.
kubeconfig_file_path: "{{ socok8s_deploy_config_location }}/kubeconfig"

suse_airship_deploy_packages:
  - ca-certificates
  - make
  - jq
  - nmap
  - uuid-runtime
  - docker
  - curl
  - python3-setuptools
  - python3-pip
  - python3-cmd2
  - python-devel

suse_airship_openstackclient_packages:
  - python3-barbicanclient
  - python3-heatclient
  - python3-openstackclient
