---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-armada
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-armada-chart-group-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  description: Armada without Tiller
  sequenced: false
  chart_group:
    - ucp-armada-soc
...
